### ISSUE TITLE
[Documentation / FAQ] Could incompatibilities be mentioned?

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-MagicStore#2]
[Documentation / FAQ] Could incompatibilities be mentioned?

If there are no known then this is also fine, just so that users may quickly see 
whether there are any issues, in particular in regards to other item-mods
(some item-mods do odd things; I assume the MagicStore is probably 
small and does not interfere with any other mod, but it would be nice
to look at that on the main README and feel assured that this is the case
so.)

**Comment by Argent77** [comment]
That's [already mentioned](https://github.com/Argent77/A7-MagicStore/blob/fd97bdc3fee3cdcfa7940e0ffe7b35dd5b5be417/A7-MagicStore/readme/readme.txt#L42-L51) in the mod's readme.
